import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./ui/home/Header";
import Stories from "./ui/home/Stories";
import Footer from "./ui/home/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"relative min-h-full"}>
        <Header />
        <Stories />
        {children}
        <Footer />
      </body>
    </html>
  );
}
